const enum ClassList {
  navButton = 'nav__button',
  navButtonActive = 'nav__button_active',
  page = 'page',
  pageHide = 'page_hide',
  pageInner = 'page__inner',
  nav = 'nav',
  main = 'main',
  title = 'title',
  button = 'button',
  subtitle = 'subtitle',
  contacts = 'contacts',
  list = 'list',
  cvSection = 'cv-section',
  cvTitle = 'cv-title',
  cvSectionName = 'cv-section__name',
  projectCardList = 'project-card-list',
  projectCard = 'project-card',
  projectCardImg = 'project-card__img',
  projectCardInfo = 'project-card__info',
  projectCardTitle = 'project-card__title',
  projectCardText = 'project-card__text',
  projectCardLinkList = 'project-card__link-list',
  projectCardLink = 'project-card__link',
  projectCardStack = 'project-card__stack',
  contactList = 'contact-list',
}

export default ClassList;
